# Generated by Django 4.0 on 2022-06-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('spirit_animal', models.CharField(max_length=100)),
                ('roles', models.CharField(choices=[('Mgr', 'Manager'), ('Emp', 'Employee'), ('Admin', 'Administrator'), ('Sup', 'Supervisor')], max_length=100)),
            ],
        ),
    ]
